-- Banco de dados do InterLink (PostgreSQL / Supabase)

-- ===== USUÁRIOS (superclasse) =====
CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            VARCHAR(100) NOT NULL,
  email           VARCHAR(150) NOT NULL UNIQUE,
  telefone        VARCHAR(20),
  senha_hash      VARCHAR(255) NOT NULL,
  tipo            VARCHAR(20)  NOT NULL
                  CHECK (tipo IN ('administrador','organizador','cliente','fornecedor')),
  status_cadastro VARCHAR(20)  NOT NULL DEFAULT 'pendente'
                  CHECK (status_cadastro IN ('pendente','aprovado','recusado')),
  criado_em       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ===== ESPECIALIZAÇÕES (1:1 com usuarios) =====
CREATE TABLE IF NOT EXISTS administradores (
  id_administrador INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario       INT NOT NULL UNIQUE REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  nivel_acesso     VARCHAR(30) NOT NULL DEFAULT 'suporte'
);

CREATE TABLE IF NOT EXISTS organizadores (
  id_organizador INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario     INT NOT NULL UNIQUE REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  cnpj           CHAR(14) NOT NULL UNIQUE,
  endereco       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS clientes (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT NOT NULL UNIQUE REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  cpf        CHAR(11) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS fornecedores (
  id_fornecedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario    INT NOT NULL UNIQUE REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  cnpj          CHAR(14) NOT NULL UNIQUE,
  endereco      VARCHAR(255)
);

-- ===== EVENTOS =====
CREATE TABLE IF NOT EXISTS eventos (
  id_evento      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_organizador INT NOT NULL REFERENCES organizadores(id_organizador),
  nome           VARCHAR(150) NOT NULL,
  data           DATE NOT NULL,
  local          VARCHAR(200),
  descricao      TEXT,
  capacidade     INT,
  status         VARCHAR(20) NOT NULL DEFAULT 'planejado'
                 CHECK (status IN ('planejado','confirmado','encerrado'))
);

-- ===== PROPOSTAS =====
CREATE TABLE IF NOT EXISTS propostas (
  id_proposta   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evento     INT NOT NULL REFERENCES eventos(id_evento),
  id_fornecedor INT NOT NULL REFERENCES fornecedores(id_fornecedor),
  data_proposta DATE NOT NULL DEFAULT CURRENT_DATE,
  data_entrega  DATE,
  status        VARCHAR(20) NOT NULL DEFAULT 'enviada'
                CHECK (status IN ('enviada','aceita','recusada')),
  valor_total   NUMERIC(10,2) NOT NULL DEFAULT 0
);

-- ===== SEGURANÇA =====
-- Bloqueia o acesso público automático do Supabase às tabelas.
-- O nosso backend continua acessando normalmente.
ALTER TABLE usuarios        ENABLE ROW LEVEL SECURITY;
ALTER TABLE administradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizadores   ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE fornecedores    ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE propostas       ENABLE ROW LEVEL SECURITY;