export const ingressos = [
  {
    id: 'festival-verao-2025',
    titulo: 'Festival de Verão 2025',
    local: 'Allianz Parque – São Paulo, SP',
    dataExibicao: '25 de Outubro, 18:00',
    dataOrdenacao: '2025-10-25',
    categoria: 'show',
    preco: 280,
    imagem: 'https://picsum.photos/seed/festival-verao-2025/160/160',
    tags: [
      { texto: 'Pista Premium' },
      { texto: 'Custódia', tipo: 'custodia' },
      { texto: 'Aceita troca', tipo: 'oferta' },
    ],
  },
  {
    id: 'campeonato-nacional',
    titulo: 'Final do Campeonato Nacional',
    local: 'Estádio do Maracanã – Rio de Janeiro, RJ',
    dataExibicao: '12 de Novembro, 21:30',
    dataOrdenacao: '2025-11-12',
    categoria: 'esporte',
    preco: 350,
    imagem: 'https://picsum.photos/seed/campeonato-nacional/160/160',
    tags: [
      { texto: 'Cadeira Inferior' },
      { texto: 'Custódia', tipo: 'custodia' },
    ],
  },
  {
    id: 'comedia-especial',
    titulo: 'Noite de Comédia Especial',
    local: 'Teatro Bradesco – São Paulo, SP',
    dataExibicao: '05 de Dezembro, 20:00',
    dataOrdenacao: '2025-12-05',
    categoria: 'teatro',
    preco: 90,
    imagem: 'https://picsum.photos/seed/comedia-especial/160/160',
    tags: [
      { texto: 'Plateia A' },
      { texto: 'Custódia', tipo: 'custodia' },
      { texto: 'Contraproposta', tipo: 'oferta' },
    ],
  },
  {
    id: 'rock-the-mountain',
    titulo: 'Rock The Mountain 2025',
    local: 'Petrópolis, RJ',
    dataExibicao: '18 de Março, Fim de Semana 1',
    dataOrdenacao: '2025-03-18',
    categoria: 'festival',
    preco: 180,
    imagem: 'https://picsum.photos/seed/rock-the-mountain/160/160',
    tags: [
      { texto: 'Passaporte 2 dias' },
      { texto: 'Custódia', tipo: 'custodia' },
    ],
  },
  {
    id: 'coldplay-brasil',
    titulo: 'Coldplay World Tour Brasil',
    local: 'Allianz Parque – São Paulo, SP',
    dataExibicao: '05 de Abril',
    dataOrdenacao: '2025-04-05',
    categoria: 'show',
    preco: 620,
    imagem: 'https://picsum.photos/seed/coldplay-brasil/160/160',
    tags: [
      { texto: 'Pista Geral' },
      { texto: 'Custódia', tipo: 'custodia' },
      { texto: 'Alta demanda', tipo: 'oferta' },
    ],
  },
]
